name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Code Coverage
        run: ./gradlew test jacocoTestReport

      - name: Run Code Climate
        env:
          CODECLIMATE_REPO_TOKEN: ${{ eeb225040771cb66c069f8c5b027d3de9f9cb0c60d7ed13addfa06a3d1291c0f }}
        run: codeclimate-test-reporter

