name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run tests
        run: ./gradlew test

      - name: Generate JaCoCo report
        run: ./gradlew jacocoTestReport

      - name: Code Coverage
        run: ./gradlew test jacocoTestReport

      - name: Verify JaCoCo report
        run: test -f build/reports/jacoco/test/jacocoTestReport.xml

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
        #run: codeclimate-test-reporter upload --input-type jacoco --output-type ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml



