clean:
	./gradlew clean

build:
	./gradlew clear build

install:
	./gradlew clean install

run:
	./gradlew run

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

lint:
	./gradlew checkstyleMain

run-dist:
		./build/install/app/bin/app
.PHONY: build

